// Use of this source code is governed by a MIT license that can be found in the LICENSE file.
// sms10086@hotmail.com

/* Automatically generated by version.sh, do not manually edit! */

package ffmpeg


//const FFMPEG_VERSION = 4.1


                          
                          

                               
